asyncFunctionCall.then( (result) => {
    return asyncFunctionCall2()
} ).then( result => {
    
}).catch( (err) => {

} )

const Person = { name: "Denilson", age: 22 }
